ALTER TABLE clubs ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(20) DEFAULT 'trial';
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(255);
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS plan_tier VARCHAR(20) DEFAULT 'free';
